# Generated by Django 3.2.19 on 2023-05-09 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_student_parent_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
