# Generated by Django 3.2.19 on 2023-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_student_parent_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
